Controllers/OrderController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ShopOnline.Data;
using ShopOnline.Utility;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ShopOnline.Controllers {
    public class OrderController : Controller {

        private readonly DataContext _db;
        private readonly UserManager<User> _userManager;
        public OrderController(DataContext db, UserManager<User> userManager) {
            _db = db;
            _userManager = userManager;
        }

        public async Task<IActionResult> Checkout() {
            string userid = HttpContext.Session.GetString("userId");
            User user = await _userManager.FindByIdAsync(userid);
            ViewData["userEmail"] = user.Email;
            ViewData["userPhone"] = user.PhoneNumber;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Checkout(Order order) {
            List<Product> products = HttpContext.Session.Get<List<Product>>("products");
            string userid = HttpContext.Session.GetString("userId");
            var GUID = Guid.NewGuid();
            order.Guid = GUID;
            order.DateTime = DateTime.Now;
            _db.Orders.Add(order);
            await _db.SaveChangesAsync();
            Order MyOrder = _db.Orders.FirstOrDefault(o => o.Guid == GUID);
            if (products != null) {
                foreach (var product in products) {
                    OrderUserProduct orderUserProduct = new() {
                        OrderId = MyOrder.Id,
                        ProductId = product.Id,
                        UserId = userid
                    };
                    _db.OrderUsers.Add(orderUserProduct);
                }
            }
            await _db.SaveChangesAsync();
            HttpContext.Session.Set("products", new List<Product>());
            return View();
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Order() {
            return View(await _db.OrderUsers.Include(o => o.Order).Include(p => p.Product).Include(u => u.User).ToListAsync());
        }
    }
}

Controllers/ProductController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ShopOnline.Data;
using System;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using X.PagedList;

namespace ShopOnline.Controllers {
    [Authorize(Roles = "Admin")]
    public class ProductController : Controller {
        private readonly DataContext _db;
        public readonly IWebHostEnvironment _he;

        public ProductController(DataContext db, IWebHostEnvironment he) {
            _db = db;
            _he = he;
        }

        public IActionResult Index(int? page) => View(Tuple.Create(_db.Products.Include(p => p.ProductTypes).Include(t => t.TagNames).ToList().ToPagedList(page ?? 1, 9), _db.Products.Count()));

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Index(string name)
        {
            if (name == null || name == "")
                return RedirectToAction(nameof(Index));

            return View(_db.Products.Include(p => p.ProductTypes).Include(t => t.TagNames).Where(p => p.Name.Contains(name)).ToList());
        }

        public IActionResult Create() {
            FillList();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Product product, IFormFile image) {
            if (!ModelState.IsValid)
                return View(product);
            
            if (IfExiste(product)) {
                ViewBag.message = "This product is already exist";
                FillList();
                return View(product);
            }

            if (image != null) {
                var name = Guid.NewGuid().ToString() + image.FileName;
                var path = Path.Combine(_he.WebRootPath + "/images", Path.GetFileName(name));
                await image.CopyToAsync(new FileStream(path, FileMode.Create));
                product.Image = name;
            } else {
                product.Image = "no-image.png";
            }

            product.Time = DateTime.Now;
            _db.Products.Add(product);
            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Edit(int? id) {
            FillList();
            var product = _db.Products.Find(id);
            return View(product);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Product product, IFormFile image) {
            if (!ModelState.IsValid) 
                return View(product);

            if (IfExiste(product)) {
                ViewBag.message = "This product is already exist";
                FillList();
                return View(product);
            }

            product.Time = DateTime.Now;
            Product oldProduct = await _db.Products.AsNoTracking().FirstOrDefaultAsync(p => p.Id == product.Id);

            if (image != null) {

                if (oldProduct.Image != "no-image.png") {
                    DeletImageFromwwwroot(oldProduct);
                }

                var newNameImage = Guid.NewGuid().ToString() + image.FileName;
                var newFullPath = Path.Combine(_he.WebRootPath + "/images", newNameImage);
                await image.CopyToAsync(new FileStream(newFullPath, FileMode.Create));

                product.Image = newNameImage;

                _db.Products.Update(product);
                await _db.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            } else {
                _db.Products.Update(product);
                _db.Entry(product).Property(p => p.Image).IsModified = false;
                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
        }

        public ActionResult Details(int? id) {
            FillList();
            if (id == null) {
                return NotFound();
            }
            var product = _db.Products.Find(id);
            if (product == null) {
                return NotFound();
            }
            return View(product);
        }

        public ActionResult Delete(int? id) {
            FillList();
            if (id == null) {
                return NotFound();
            }
            var product = _db.Products.Find(id);
            if (product == null) {
                return NotFound();
            }
            return View(product);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(Product product) {
            Product oldProduct = await _db.Products.AsNoTracking().FirstOrDefaultAsync(p => p.Id == product.Id);

            if (product.Image != "no-image.png") {
                DeletImageFromwwwroot(oldProduct);
            }

            _db.Products.Remove(product);
            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> DeleteImage(int id) {
            Product product = await _db.Products.AsNoTracking().FirstOrDefaultAsync(p => p.Id == id);

            if (product.Image == "no-image.png") 
                return RedirectToAction(nameof(Index));

            DeletImageFromwwwroot(product);

            product.Image = "no-image.png";

            _db.Products.Update(product);
            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public void FillList() {
            ViewBag.ProductTypeId = new SelectList(_db.ProductsTypes.ToList(), "Id", "Name");
            ViewBag.TagNameId = new SelectList(_db.TagNames.ToList(), "Id", "Name");
        }

        private bool IfExiste(Product product) {
            var searchProductType = _db.Products.FirstOrDefault(p => p.Name == product.Name && p.Id != product.Id);
            if (searchProductType != null) {
                return true;
            }
            return false;
        }

        public void DeletImageFromwwwroot(Product product) {
            var oldNameImage = product.Image;
            var oldFullPath = Path.Combine(_he.WebRootPath + "/images", oldNameImage);
            System.IO.File.Delete(oldFullPath);
        }
    }
}

Controllers/RoleController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ShopOnline.Data;
using ShopOnline.Models;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ShopOnline.Controllers {
    [Authorize(Roles = "Admin")]
    public class RoleController : Controller {
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly UserManager<User> _userManager;
        private readonly DataContext _db;

        public RoleController(RoleManager<IdentityRole> roleManager, DataContext db, UserManager<User> userManager) {
            _roleManager = roleManager;
            _userManager = userManager;
            _db = db;
        }

        public async Task<IActionResult> Index() {
            var roles = await _db.Roles.AsNoTracking().ToListAsync();
            return View(roles);
        }

        [HttpGet]
        public IActionResult Create() => View();

        [HttpPost]
        public async Task<IActionResult> Create(string roleName) {
            await _roleManager.CreateAsync(new IdentityRole { Name = roleName });
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public IActionResult Delete(string id) {
            var role = _db.Roles.Find(id);
            return View(role);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirm(string id) {
            var role = await _roleManager.FindByIdAsync(id);
            await _roleManager.DeleteAsync(role);
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public IActionResult Assign() => View(FillList());

        [HttpPost]
        public async Task<IActionResult> Assign(UserRoleDto userRoleDto) {
            User user = await _userManager.FindByIdAsync(userRoleDto.UserId);
            IdentityRole role = await _roleManager.FindByIdAsync(userRoleDto.RoleId);
            if (user == null || role == null) {
                return View(FillList());
            }
            var uerRole = _db.UserRoles.FirstOrDefault(U => U.UserId == userRoleDto.UserId);
            if (uerRole != null) {
                ViewBag.haveRole = "This user already have role";
                return View(FillList());
            }
            await _userManager.AddToRoleAsync(user, role.Name);
            return RedirectToAction(nameof(UserRole));
        }

        public ActionResult UserRole() {
            var result = from ur in _db.UserRoles
                         join r in _db.Roles on ur.RoleId equals r.Id
                         join a in _db.Users on ur.UserId equals a.Id
                         select new UserRoleMapingDto() {
                             UserId = ur.UserId,
                             RoleId = ur.RoleId,
                             UserEmail = a.Email,
                             RoleName = r.Name
                         };

            /*
                SELECT ur.UserId UserId, ur.RoleId RoleId, a.Email Email, r.Name RoleName
                FROM UserRoles ur
                INNER JOIN Users a ON a.Id = ur.userId
                INNER JOIN Roles r ON r.Id = ur.roleId
             */

            ViewBag.UserRoles = result;
            return View();
        }

        public UserRoleDto FillList() {
            List<IdentityRole> roles = _db.Roles.ToList();
            List<User> users = _db.Users.ToList();
            UserRoleDto userRole = new(roles, users);
            return userRole;
        }
    }
}

Controllers/UserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ShopOnline.Data;
using System;
using System.Threading.Tasks;

namespace ShopOnline.Controllers {
    [Authorize(Roles = "Admin")]
    public class UserController : Controller {
        private readonly DataContext _db;
        public UserController(DataContext db) {
            _db = db;
        }
        public async  Task<IActionResult> Index() {
            var users = await _db.Users.ToListAsync();
            return View(users);
        }

        public async Task<IActionResult> ActiveUser(string id) {
            var user = _db.Users.Find(id);
            user.LockoutEnd = null;
            _db.Users.Update(user);
            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> DeactiveUser(string id) {
            var user = _db.Users.Find(id);
            user.LockoutEnd = DateTime.Now.AddYears(100);
            _db.Users.Update(user);
            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> DeleteUser(string id) {
            var user = _db.Users.Find(id);
            _db.Users.Remove(user);
            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using ShopOnline.Data
@using ShopOnline.Utility
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor
@inject SignInManager<User> SignInManager

@{ 
    int count = 0;
    List<Product> products = HttpContextAccessor.HttpContext.Session.Get<List<Product>>("products");
    if (products == null) {
        products = new List<Product>();
    }
    count = products.Count();
    var role = HttpContextAccessor.HttpContext.Session.GetString("role");
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ShopOnline</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">ShopOnline</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (role == "Admin") {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="User" asp-action="Index">User</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Role" asp-action="Index">Role</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Role" asp-action="UserRole">User To Role</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="ProductType" asp-action="Index">Product Type</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="TagName" asp-action="Index">Tag Name</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Product" asp-action="Index">Product</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Order" asp-action="Order">Order</a>
                            </li>
                        }
                        <li>
                            <a class="nav-link text-dark" asp-controller="Home" asp-action="Cart"><i class="fas fa-shopping-cart"></i>(@count)</a>
                        </li>
                    </ul>
                    @if (SignInManager.IsSignedIn(User)) {
                        <ul class="nav navbar-nav navbar-right">
                            <li>
                                <a class="nav-link text-dark" asp-controller="Account" asp-action="Logout">Logout</a>
                            </li>
                        </ul>
                    } else {
                        <ul class="nav navbar-nav navbar-right">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Account" asp-action="Register">Register</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Account" asp-action="Login">Login</a>
                            </li>
                        </ul>
                    }
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - ShopOnline - <a asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://kit.fontawesome.com/12a439e757.js" crossorigin="anonymous"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>